import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import prismaClient from '../../prisma/Client'
import { Tours } from '@prisma/client'



export async function getServerSideProps() {
    const list = await prismaClient.tours.findMany()
    list.map(item => {
        item.time = item.time.toDateString() as any
        return item
    })
    return {
      props: {list}, // will be passed to the page component as props
    }
}

const Page: NextPage<{list:Tours[]}> = ({list}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {list.map(item => <li key={item.id}>Название: {item.name}, Время: {item.time.toString()}</li>)}
      </ul>
    </div>
  )
}

export default Page